proxyCount: 1
keysPerProxy: 2

onePod:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  host: ""

image:
  repository: neonlabsorg/proxy
  pullPolicy: Always
  tag: "v1.11.3"

resources:
  requests:
    cpu: 500m
    memory: 2G        
  limits:
    cpu: 1000m            
    memory: 4G

serviceAccount:
  create: true
  annotations: {}
  name: "neon-proxy-sa"

securityContext:
  seccompProfile:
    type: RuntimeDefault
  privileged: false
  allowPrivilegeEscalation: false
  #runAsUser: 2000

podAnnotations: {}

service:
  name: proxy-svc
  type: ClusterIP
  sessionAffinity: ClientIP
  clusterIP: None
  port: 9090
  protocol: TCP
  labels: {}

extraPorts:
  - port: 9092
    containerPort: 9092
    protocol: TCP
    name: service-port
  - port: 8888
    containerPort: 8888
    protocol: TCP
    name: exporter

envFrom:
  - secretRef: 
      name: postgres-secret
  - secretRef: 
      name: proxy-config

ENABLE_SEND_TX_API: "YES"

proxyEnv: {}

solanaUrl: ""
evm_loader: ""
ppsolanaUrl: ""

volumes: 
  - name: proxy-keys-script
    configMap:
      name: proxy-keys-script
      defaultMode: 0777

volumeMounts: 
  - name: proxy-keys-script
    mountPath: /root/.config/solana/scripts/get_keys.sh
    subPath: get_keys.sh
  - name: proxy-keys-script
    mountPath: /opt/proxy/run-proxy.sh
    subPath: run-proxy.sh
  - name: proxy-keys-script
    mountPath: /opt/proxy/run-indexer.sh
    subPath: run-indexer.sh
  - name: proxy-keys-script
    mountPath: /opt/run-gas-tank.sh
    subPath: run-gas-tank.sh

workingDir: "/opt"

indexer:
  service:
    name: indexer-svc
    type: ClusterIP
    port: 8888
    protocol: TCP
  indexerKey: ""
  labels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
 



